### ISSUE TITLE
SSL verification error in conda in Mac OS X Sierra

### ISSUE THREAD

**Issue by OrbitalMechanic** [ContinuumIO/anaconda-verify#11]
I'm running conda ver. 4.1.12 on a Mac Pro running Mac OS X Sierra (10.12.1). I was attempting to install the package astroplan. I got error messages saying that the SSL module was not available.

Now this is the first time running under Mac OS X Sierra that I got SSL verification error messages. I did check the settings in my .condarc file and found that ssl_verify: true.

I've attached a file containing the error message and the reults of using the conda info -a command.

Please advise.

Sam Dupree.

[SSL_verificatin_error_conda.txt](https://github.com/ContinuumIO/anaconda-verify/files/572689/SSL_verificatin_error_conda.txt)

**Comment by ilanschnell** [comment]
I think this issue belongs here: https://github.com/conda/conda
CC @kalefranz
