### ISSUE TITLE
`extra` section in `meta.yaml` unsupported?

### ISSUE THREAD

**Issue by jakirkham** [ContinuumIO/anaconda-verify#3]
After taking an existing [recipe](https://github.com/conda-forge/yt-feedstock/tree/307607a0be698105aa62799f4a625380d3a4c468/recipe) and running `conda rerender` on it (with the needed NumPy version), I generated a new static `meta.yaml` file that does not have Jinja so as to avoid this issue ( https://github.com/ContinuumIO/anaconda-verify/issues/2 ). When running `anaconda-verify` on this, I run into a new issue. It appears the `extra` section is unsupported. 😕

```
==> recipe/ <==
RecipeError: Unknown section: extra
```

cc @pelson @ocefpaf @msarahan

**Comment by ilanschnell** [comment]
The internal Anaconda build system does not require the `extra` section, and we want to keep the recipes as simple an minimal as possible.

**Comment by ilanschnell** [comment]
I guess the discussion in #2 answers this question as well.

**Comment by jakirkham** [comment]
Agreed, thanks for clarifying.

**Comment by ilanschnell** [comment]
In version 1.2.0, which I just released, a `--pedantic` option was added.  Without this option (by default), having the `extra` section is fine.
