### ISSUE TITLE
Publish to PyPI

### ISSUE THREAD

**Issue by jmchilton** [ContinuumIO/anaconda-verify#8]
This project is very well self-contained and doesn't seem to depend on anything but itself. It would be awesome if you'd publish it to PyPI. This isn't me trolling I promise - I work on a tool developer-oriented  project that gets published to PyPI and bioconda and I'd love to _cleanly_ reuse this as a library to assist in conda recipe development. I'll do some hacking for now - but the _cleanly_ part would be nice.

Thanks!

**Comment by ilanschnell** [comment]
If you are using this tool, you are already using `conda` already (to verify conda recipes and packages), and conda packages of `anaconda-verify` are always being made available in the default channel.  If you want to use the development version on github, you just do a `git clone` and and the location to a `.pth` file.
Can you please help me understand what your usecase is?  Thanks
